version: '2'
services:
  web:
    image: nk2016_web
    ports: 
      - "8888:8888"
    volumes_from:
      - nk2016_hostdata
    depends_on:
      - mongo
      - redis
    links:
      - mongo
      - redis
    tty: true # to keep it alive, however this triggers http error exception on docker-compose up(container still running ,though)
      
  mongo:
    image: mongo
    volumes_from:
      - nk2016_mongodata
  
  redis: # todo: persistence
    image: redis
    volumes_from:
      - nk2016_redisdata

  nk2016_hostdata: # can be mounted and used as data volume even stopped.
    image: ubuntu
    volumes:
      - ~/nk2016:/hostdata:rw
   
  nk2016_mongodata:
    image: ubuntu
    volumes:
      - ~/nk2016/dbdata:/data/db:rw
  
  nk2016_redisdata:
    image: ubuntu
    volumes:
      - ~/nk2016/redisdata:/data:rw
